### ISSUE TITLE
How to Contribute?

### ISSUE THREAD

**Issue by aliifam** [ardhptr21/candaan-api#1]
bro kalo mau kontribusi data jokes receh gimana nih prosedurnya?

**Comment by ardhptr21** [comment]
Gampang kak, langsung aja tambah data nya di folder `/data/api`, nah nanti ada 2 file, yaitu `text.json` sama `image.json`, nah langsung aja deh masukkin data baru nya mau tipe nya text atau image.

*Sorry for the late replay*
